---
- name: Delete system from Satellite
  hosts: sat.example.com
  remote_user: root

  tasks:

    - name: Get host information
      shell: hammer --csv host list --search="{{ vm_fq_hostname }}" | grep -vi '^ID' | awk -F, {'print $1'}
      register: host_info

    - name: Delete the host from Satellite
      shell: hammer host delete --id "{{ host_info.stdout }}"
      when: host_info.stdout
