---
- name: Un-register system from Satellite
  hosts: "{{ vm_fq_hostname | default('NO_HOSTS') }}"
  remote_user: root

  tasks:

    - name: Ensure system is unregistered
      redhat_subscription:
        state: absent
